all:
	javac -encoding UTF-8 Hello.java -classpath "../.."
	javac -encoding UTF-8 Frequencer.java -classpath "../.."
	javac -encoding UTF-8 InformationEstimator.java -classpath "../.."
	javac -encoding UTF-8 TestCase.java -classpath "../.."
	javac -encoding UTF-8 FrequencerNaive.java -classpath "../.."
	javac -encoding UTF-8 InformationEstimatorNaive.java -classpath "../.."
run:
	java -classpath "../.." s4.B233375/Hello
	java -classpath "../.." s4.B233375/Frequencer
	java -classpath "../.." s4.B233375/InformationEstimator
	java -ea -classpath "../.." s4.B233375/TestCase
	java -classpath "../.." s4.B233375/FrequencerNaive
	java -classpath "../.." s4.B233375/InformationEstimatorNaive
clean:
	rm -f *.class *~


